### ISSUE TITLE
disconnect does not trigger "leaves zone" event in HA

### ISSUE THREAD

**Issue by bjo81** [awilliams/wifi-presence#24]
The card with the status of the device shows "away" in HA, but the trigger is never triggered. Maybe it's an issue on HA's side.

**Comment by awilliams** [comment]
@bjo81 could you share the YAML you're using?

This is part of a trigger I have setup that's working:

```yaml
platform: state
entity_id: group.home_presence
to: not_home
```
